const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs'); // read environment variables from .env file

require('dotenv').config();// read the command line arguments passed with yargs
const environment = argv.environment;


function writeFileUsingFS(targetPath: any, environmentFileContent: any) {
   writeFile(targetPath, environmentFileContent, function(err: any) {
      if(err) {
         console.log(err)
      }

      if(environmentFileContent !== '') {
         console.log(`Wrote variables to ${targetPath}`)
        if(process.env.Targomo_API_KEY) {
          console.log('Got Key')
        }
      }
   })
}

const envDirectory = './src/environments';

if(!existsSync(envDirectory)) {
   mkdirSync(envDirectory)
}

writeFileUsingFS('./src/environments/environment.prod.ts', '')
writeFileUsingFS('./src/environments/environment.ts', '')


const isProduction = true
const prodPath = `./src/environments/environment.prod.ts`
const path =  `./src/environments/environment.ts`;

const environmentFileContent = `// This file wsa autogenerated by running setenv.ts and using dotenv
export const environment = {
   production: ${isProduction},
   Targomo_API_KEY: "${process.env.Targomo_API_KEY}",
   MapBox_API_KEY: "${process.env.MapBox_API_KEY}"
};
`;


writeFileUsingFS('./src/environments/environment.prod.ts', '')
writeFileUsingFS('./src/environments/environment.ts', '')

writeFileUsingFS(prodPath, environmentFileContent)
writeFileUsingFS(path, environmentFileContent)
