const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs'); // read environment variables from .env file

require('dotenv').config();// read the command line arguments passed with yargs
const environment = argv.environment;


function writeFileUsingFS(targetPath: any, environmentFileContent: any) {
   writeFile(targetPath, environmentFileContent, function(err: any) {
      if(err) {
         console.log(err)
      }

      if(environmentFileContent !== '') {
         console.log(`Wrote variables to ${targetPath}`)
      }
   })
}

const envDirectory = './src/environments';

if(!existsSync(envDirectory)) {
   mkdirSync(envDirectory)
}

writeFileUsingFS('./src/environments/environment.prod.ts', '')
writeFileUsingFS('./src/environments/environment.ts', '')



const isProduction = environment === 'prod';
const targetPath = isProduction
   ? `./src/environments/environment.prod.ts`
   : `./src/environments/environment.ts`; // we have access to our environment variables
// in the process.env object thanks to dotenv

const environmentFileContent = `// This file wsa autogenerated by running setenv.ts and using dotenv
export const environment = {
   production: ${isProduction},
   Targomo_API_KEY: "${process.env.Targomo_API_KEY}",
   MapBox_API_KEY: "${process.env.MapBox_API_KEY}"
};
`;

writeFileUsingFS(targetPath, environmentFileContent)