name: Build and Deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    name: Building page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install
             npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Upload math result for build job
        uses: actions/upload-artifact@v2
        with:
          name: webpage
          path: dist/
          
  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Getting folder
        uses: actions/download-artifact@v2
        with:
            name: webpage

      - name: Copying folder
        uses: s0/git-publish-subdir-action@develop
        env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: quality-demo
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
