name: Build and Deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    name: Building page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install
             npm run build
      - run: ls ${{ github.workspace }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: webpage
          path: ${{ github.workspace }}/dist/
       

    
