name: Build and Deploy
on:
  push:
    branches:
      - main
      
  workflow_dispatch:
  
  
jobs:

  secrets-in-github-actions:
    runs-on: ubuntu-latest

    steps:
      # Use a GitHub Actions secret variable in a bash shell
      - name: Setting Targomo API Key
        shell: bash
        env: 
          Targomo_API_KEY: ${{ secrets.Targomo_API_KEY }}
          MapBox_API_KEY: ${{ secrets.MapBox_API_KEY }}
        run: echo "Ready to go!"


  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm ci
    - name: Build page
      run: npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist/quality-demo

    
