name: Setting up API Key

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest

    steps:
      # Use a GitHub Actions secret variable in a bash shell
      - name: Setting Targomo API Key
        shell: bash
        env: 
          Targomo_API_KEY: ${{ secrets.Targomo_API_KEY }}
          MapBox_API_KEY: ${{ secrets.MapBox_API_KEY }}
        run: echo "Ready to go!"

